### PR TITLE
K smallest elements

### PR DESCRIPTION
**Pull request by Kaisle**
To find the k smallest elements we:

1) Create a new PQ, fpq. 
2) Add the root to fpq.
3) Poll the fpq.
4) Add the two children of the polled element to the fpq.
5) Repeat step 3-4 k times

Total complexity: O (k log k). Just polling the entire queue k times and adding each element back is O (k log n). So if k is much smaller than n this provides a significant speedup.

Process is described in detail here: https://stackoverflow.com/questions/7650917/oklogk-time-algorithm-to-find-kth-smallest-element-from-a-binary-heap

### CODE REVIEW

**Comment by Kaisle** [comment]
Just realized the comparator of the first queue obviously has to be passed on to the second queue. And it needs to compare the data attribute only.

**Comment by lemire** [comment]
@Kaisle Would you consider something simpler (and probably faster) like...

```javascript
FastPriorityQueue.prototype.kSmallest = function(k) {
  if (this.size == 0) return [];
  var comparator = this.compare;
  var fpq = new FastPriorityQueue(function(a,b){ 
   return comparator(this.array[a],this.array[b]); 
  });
  k = Math.min(this.size, k);
  var smallest = new Array(k);
  var j = 0;
  fpq.add(0);
  while (j < k) {
    var small = fpq.poll();
    smallest[j++] = this.array[small];
    var l = (small << 1) + 1;
    var r = l + 1;
    if (l < this.size) fpq.add(l);
    if (r < this.size) fpq.add(r);
  }
  return smallest;
}
```

(This is untested code.)

It seems that there are just far fewer things going on in such a simpler version... so I would expect the compiler to have an easier time.

**Comment by Kaisle** [comment]
Great job on simplifying it. Should indeed be easier on the compiler. I'm all for speed and simplicity.

**Comment by lemire** [comment]
@Kaisle  Want to update your PR?

Alternatively, I can merge and then edit your code, but it would be cleaner to merge something you have tuned.

**Comment by lemire** [comment]
Ping?

**Pull request merged**
