### PR TITLE
Port to typescript

### PR DESCRIPTION
**Pull request by ddurschlag6river**
`npm i; npm test` to build and run tests. I disabled the "main" code which did module magic I didn't know how to write in typescript.

### CODE REVIEW

**Comment by lemire** [comment]
Thanks.

**Comment by ddurschlag6river** [comment]
Do you intend to eventually merge this, or shall I fork and publish separately?

**Comment by lemire** [comment]
@ddurschlag6river 

Honestly, I don't know how to handle your PR.

I don't mind typescript, but I hate to make it a requirement on people who prefer JavaScript.

**Comment by ddurschlag6river** [comment]
Well, typescript compiles to javascript -- people who use pure javascript can still reference the package.

That said, for now I've simply forked the code and published under the name typedpriorityqueue on npm. You're welcome to pull it down and try it out from javascript yourself.

**Comment by lemire** [comment]
Oh! I know typescript goes to javascript. 😀

**Comment by lemire** [comment]
Please merge with master. We need to assess the performance consequences of this PR. The new travis script ensures that benchmarks are run.

**Comment by ddurschlag6river** [comment]
I published this separately (https://www.npmjs.com/package/typedpriorityqueue and https://github.com/ddurschlag6river/TypedPriorityQueue), and there are now conflicts with this branch. You're welcome to fix those up and merge it if you'd like, but I'm going to use/maintain my fork as necessary.

**Comment by lemire** [comment]
Thanks. As for myself, I am fine with the fork. Note that we have a contributor file now that you may want to reuse to make sure that credit is given.

I'm going to close this as it seems that there is no need to merge. Reopen if you disagree.

**Pull request closed without merging**
